### ISSUE TITLE
[iOS] Memory leak in updating TextArea

### ISSUE THREAD

**Issue by jackyy415** [codenameone/CodenameOne#1577]
There is memory leak in iOS when TextArea(maybe Label as well) setText() is called.
The following codes can reproduce the issue after pressing the button for hundred times within a short period. The memory goes up after pressing the button and the memory will not be released. Please note that you have to press the button quickly for multiple times.

protected void onMain_TestLabel2Action(Component c, ActionEvent event) {
        int iCounter = 0;
        while (iCounter < 100) {
            TextArea testTxtArea = findRandomTextArea(c);
            testTxtArea.setText("Random100_" + new Date().getTime());
            testTxtArea.getParent().revalidate();
            iCounter++;
        }
 }

**Comment by codenameone** [comment]
Steve, can you see if you can reproduce this in a clean test case?
Can you isolate if this is a newVM only issue or a generic issue?

**Comment by shannah** [comment]
I can't seem to reproduce this.  Here is my test case:

~~~~
package com.codename1.tests.issue1577;


import com.codename1.ui.Button;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.TextArea;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.io.IOException;
import java.util.Date;

public class TextAreaMemoryLeakIssue1577 {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        try {
            theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            e.printStackTrace();
        }
        // Pro users - uncomment this code to get crash reports sent to you automatically
        /*Display.getInstance().addEdtErrorHandler(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                evt.consume();
                Log.p("Exception in AppName version " + Display.getInstance().getProperty("AppVersion", "Unknown"));
                Log.p("OS " + Display.getInstance().getPlatformName());
                Log.p("Error " + evt.getSource());
                Log.p("Current Form " + Display.getInstance().getCurrent().getName());
                Log.e((Throwable)evt.getSource());
                Log.sendLog();
            }
        });*/
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World");
        hi.setLayout(new BorderLayout());
        TextArea ta = new TextArea();
        
        Button btn = new Button("Click Me Repeatedly");
        btn.addActionListener((evt)-> {
            ta.setText("Random100_" + new Date().getTime());
        });
        hi.addComponent(BorderLayout.NORTH, btn);
        hi.addComponent(BorderLayout.CENTER, ta);
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }

}
~~~~

Tried clicking repeatedly for about 10 minutes and memory stayed stable.  Running on iOS 8.2 iPhone 6 simulator (through Xcode) (new VM).

@jackyy415 Can you confirm whether this test case cause a memory leak in your environment?  If not, can you adjust this test case to produce the issue?

**Comment by jackyy415** [comment]
This case cannot causes the memory leak in my environment. I've created the test case which can reproduce the problem. It is a very simple project which is similar to yours.

The differences between my project and your sample project are shown as below:
1) the button and the textearea are added via the GUI Builder and the UI is loaded by theme.res.
2) when the button is clicked/pressed, the setText() will be called for multiple times. In order to speed up the testing, the setText() will be called for 1000 times for each click.

The memory goes up to > 100mb after clicking repeatedly for just 1 or 2 minutes.

Sample project link:
1) Codeaname One project:
https://drive.google.com/file/d/0B3VEmM6wQ_-IYXJPZkp1eGxSTkE/view?usp=sharing

2) Built iOS project 
https://drive.google.com/file/d/0B3VEmM6wQ_-IWmVNMDVuS0c3Zjg/view?usp=sharing

Thanks

**Comment by codenameone** [comment]
Can you update the test case so we can see the exact differences?
Please use github so we can easily review the code instead of drive. Thanks.

**Comment by jackyy415** [comment]
Hi,

As mentioned before, I cannot update your test case to reproduce the issue as your test case does not involve UIBuilder.

My test case used the UI Builder to build the whole UI and thus the situation is totally different. It is difficult to post the code here as I create the UI via drag and drop by the UIBuilder.

Instead, I will show my StateMachineBase and StateMachine codes to you. I know it's hard to read but that's the problem can be reproduced only when the UI is created by UIBuilder. 

------------------------------------------------------------------------------------------------------------
StateMachineBase.java

package generated;

import com.codename1.ui.*;
import com.codename1.ui.util.*;
import com.codename1.ui.plaf.*;
import java.util.Hashtable;
import com.codename1.ui.events.*;

public abstract class StateMachineBase extends UIBuilder {
    private Container aboutToShowThisContainer;

    protected void initVars() {}

    protected void initVars(Resources res) {}

    public StateMachineBase(Resources res, String resPath, boolean loadTheme) {
        startApp(res, resPath, loadTheme);
    }

    public Container startApp(Resources res, String resPath, boolean loadTheme) {
        initVars();
        UIBuilder.registerCustomComponent("Button", com.codename1.ui.Button.class);
        UIBuilder.registerCustomComponent("Form", com.codename1.ui.Form.class);
        UIBuilder.registerCustomComponent("TextArea", com.codename1.ui.TextArea.class);
        if(loadTheme) {
            if(res == null) {
                try {
                    if(resPath.endsWith(".res")) {
                        res = Resources.open(resPath);
                        System.out.println("Warning: you should construct the state machine without the .res extension to allow theme overlays");
                    } else {
                        res = Resources.openLayered(resPath);
                    }
                } catch(java.io.IOException err) { err.printStackTrace(); }
            }
            initTheme(res);
        }
        if(res != null) {
            setResourceFilePath(resPath);
            setResourceFile(res);
            initVars(res);
            return showForm(getFirstFormName(), null);
        } else {
            Form f = (Form)createContainer(resPath, getFirstFormName());
            initVars(fetchResourceFile());
            beforeShow(f);
            f.show();
            postShow(f);
            return f;
        }
    }

    protected String getFirstFormName() {
        return "Main";
    }

    public Container createWidget(Resources res, String resPath, boolean loadTheme) {
        initVars();
        UIBuilder.registerCustomComponent("Button", com.codename1.ui.Button.class);
        UIBuilder.registerCustomComponent("Form", com.codename1.ui.Form.class);
        UIBuilder.registerCustomComponent("TextArea", com.codename1.ui.TextArea.class);
        if(loadTheme) {
            if(res == null) {
                try {
                    res = Resources.openLayered(resPath);
                } catch(java.io.IOException err) { err.printStackTrace(); }
            }
            initTheme(res);
        }
        return createContainer(resPath, "Main");
    }

    protected void initTheme(Resources res) {
            String[] themes = res.getThemeResourceNames();
            if(themes != null && themes.length > 0) {
                UIManager.getInstance().setThemeProps(res.getTheme(themes[0]));
            }
    }

    public StateMachineBase() {
    }

    public StateMachineBase(String resPath) {
        this(null, resPath, true);
    }

    public StateMachineBase(Resources res) {
        this(res, null, true);
    }

    public StateMachineBase(String resPath, boolean loadTheme) {
        this(null, resPath, loadTheme);
    }

    public StateMachineBase(Resources res, boolean loadTheme) {
        this(res, null, loadTheme);
    }

    public com.codename1.ui.TextArea findRandomTextArea(Component root) {
        return (com.codename1.ui.TextArea)findByName("RandomTextArea", root);
    }

    public com.codename1.ui.TextArea findRandomTextArea() {
        com.codename1.ui.TextArea cmp = (com.codename1.ui.TextArea)findByName("RandomTextArea", Display.getInstance().getCurrent());
        if(cmp == null && aboutToShowThisContainer != null) {
            cmp = (com.codename1.ui.TextArea)findByName("RandomTextArea", aboutToShowThisContainer);
        }
        return cmp;
    }

    public com.codename1.ui.Button findTestLabel2(Component root) {
        return (com.codename1.ui.Button)findByName("TestLabel2", root);
    }

    public com.codename1.ui.Button findTestLabel2() {
        com.codename1.ui.Button cmp = (com.codename1.ui.Button)findByName("TestLabel2", Display.getInstance().getCurrent());
        if(cmp == null && aboutToShowThisContainer != null) {
            cmp = (com.codename1.ui.Button)findByName("TestLabel2", aboutToShowThisContainer);
        }
        return cmp;
    }

    protected void exitForm(Form f) {
        if("Main".equals(f.getName())) {
            exitMain(f);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void exitMain(Form f) {
    }

    protected void beforeShow(Form f) {
    aboutToShowThisContainer = f;
        if("Main".equals(f.getName())) {
            beforeMain(f);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void beforeMain(Form f) {
    }

    protected void beforeShowContainer(Container c) {
        aboutToShowThisContainer = c;
        if("Main".equals(c.getName())) {
            beforeContainerMain(c);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void beforeContainerMain(Container c) {
    }

    protected void postShow(Form f) {
        if("Main".equals(f.getName())) {
            postMain(f);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void postMain(Form f) {
    }

    protected void postShowContainer(Container c) {
        if("Main".equals(c.getName())) {
            postContainerMain(c);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void postContainerMain(Container c) {
    }

    protected void onCreateRoot(String rootName) {
        if("Main".equals(rootName)) {
            onCreateMain();
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void onCreateMain() {
    }

    protected Hashtable getFormState(Form f) {
        Hashtable h = super.getFormState(f);
        if("Main".equals(f.getName())) {
            getStateMain(f, h);
            aboutToShowThisContainer = null;
            return h;
        }

            return h;
    }


    protected void getStateMain(Form f, Hashtable h) {
    }

    protected void setFormState(Form f, Hashtable state) {
        super.setFormState(f, state);
        if("Main".equals(f.getName())) {
            setStateMain(f, state);
            aboutToShowThisContainer = null;
            return;
        }

            return;
    }


    protected void setStateMain(Form f, Hashtable state) {
    }

    protected void handleComponentAction(Component c, ActionEvent event) {
        Container rootContainerAncestor = getRootAncestor(c);
        if(rootContainerAncestor == null) return;
        String rootContainerName = rootContainerAncestor.getName();
        Container leadParentContainer = c.getParent().getLeadParent();
        if(leadParentContainer != null && leadParentContainer.getClass() != Container.class) {
            c = c.getParent().getLeadParent();
        }
        if(rootContainerName == null) return;
        if(rootContainerName.equals("Main")) {
            if("TestLabel2".equals(c.getName())) {
                onMain_TestLabel2Action(c, event);
                return;
            }
            if("RandomTextArea".equals(c.getName())) {
                onMain_RandomTextAreaAction(c, event);
                return;
            }
        }
    }

      protected void onMain_TestLabel2Action(Component c, ActionEvent event) {
      }

      protected void onMain_RandomTextAreaAction(Component c, ActionEvent event) {
      }

}


---------------------------------------------------------------------------------------------------------

StateMachine.java

package userclasses;

import com.codename1.ui.Component;
import com.codename1.ui.TextArea;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.util.Resources;
import generated.StateMachineBase;

import java.util.Date;

public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }

    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
    }

    public static int byteArrayToInt(byte[] b) {
        return b[3] & 0xFF |
                (b[2] & 0xFF) << 8 |
                (b[1] & 0xFF) << 16 |
                (b[0] & 0xFF) << 24;
    }

    public static byte[] intToByteArray(int a) {
        return new byte[]{
                (byte) ((a >> 24) & 0xFF),
                (byte) ((a >> 16) & 0xFF),
                (byte) ((a >> 8) & 0xFF),
                (byte) (a & 0xFF)
        };
    }

    @Override
    protected void onMain_TestLabel2Action(Component c, ActionEvent event) {
        int iCounter = 0;
        while (iCounter < 1000) {
            TextArea testTxtArea = findRandomTextArea(c);
            testTxtArea.setText("Random1000_" + new Date().getTime());
            testTxtArea.getParent().revalidate();
            iCounter++;
        }
    }

}

**Comment by jackyy415** [comment]
Hi Shai,

Any news on this issue? We are still waiting for the fix before deploying it to production.

Thanks.

Best Regards,
Jacky Yuen

**Comment by codenameone** [comment]
If you edit Steve's test case and change 

        btn.addActionListener((evt)-> {
            int iCounter = 0;
            while (iCounter < 1000) {
               ta.setText("Random1000_" + new Date().getTime());
               ta.getParent().revalidate();
               iCounter++;
               ta.setText("Random100_" + new Date().getTime());
            }
        });

Does this reproduce the issue?

That might actually be a leak of String objects which have special storage behavior.

**Comment by jackyy415** [comment]
Hi Shai,

No, it cannot reproduce the problem. 

Can you just download my project which is very simple and start the debugging with my project?

Thanks

Regards,
Jacky Yuen

**Comment by shannah** [comment]
I downloaded your project and ran it with the Allocations instrument in Xcode.  While the responsiveness is terrible (for obvious reasons), the persistent bytes seems to be stable.

I.e.  I cannot reproduce a leak with your project.

What process were you using to identify a leak?

**Comment by jackyy415** [comment]
You can identity the leak by using the "Mark Generation" in Instrument.
1) After launching the app, click "Mark Generation" on the right panel to mark the memory usage snapshot as a base.
2) Click the "Update TextArea X 1000 times" button for 20 times. Click "Mark Generation" again and it tells you the memory usage difference between current and previous generation. You should notice > 1MB is shown at the "Growth" column which means the memory usage has grown. If the memory is released, the "Growth" column will reflect the change.
3) Repeat step 2 for several times and you should notice the memory usage grows at each generation and the memory usage is not released.

You can expand the generations to check which objects occupied the memory and not released.
It showed some bytes are occupied by codenameOneGcMalloc. codenameOneGcMalloc was called by different methods but they are mainly about String/Font. For example, FontStringCache, StringBuilder.toString(), Font.stringWidth, Font.charsWidth, [DrawString execute], etc....

The sample screenshots are attached in this comment.

![generation_screenshot](https://cloud.githubusercontent.com/assets/13036432/10037146/94364b12-61e4-11e5-9338-cc7e2a35564d.JPG)

![generation_screenshot2](https://cloud.githubusercontent.com/assets/13036432/10037150/a1c1fec0-61e4-11e5-81bc-b69bba11e43a.JPG)

**Comment by jackyy415** [comment]
Hi,

As the screenshot and the steps to detect memory leak have been attached for few days, is there any news? We are still waiting the result before deployment.

Thanks.

Best Regards,
Jacky Yuen

**Comment by codenameone** [comment]
Hi,
I'm waiting for @shannah to second this but that doesn't look like a memory leak. Our GC is invisible to Objective-C and to most of Apple's tools.

**Comment by jackyy415** [comment]
Hi,

For this case, the instrument shows the memory is never released even I have waited for a long time. If the CodenameOne GC works fine, the memory should be released at some point. The instrument should show the real memory usage as it shows the very low level byte allocation as well.

Furthermore, my app will be crashed after updating the textarea for many times over a long time while the app is very stable if I have disabled updating the textarea.

Can you please double check it? If this issue cannot be fixed, our app cannot be deployed and we may need to leave Codename One and seek for another framework.

Thanks.

Best Regards,
Jacky Yuen

**Comment by shannah** [comment]
I'm also not yet convinced that it is a memory leak.  When running the demo app in the simulator with instruments, it caused my computer to run really slowly.  Yet, I didn't see much memory growth.
A little bit of growth is expected since there is a string texture cache that will grow until it is full - and won't be released... when it fills it just acts as an LRU cache.

I will look at it again today to see if I can see any evidence of a leak.

**Comment by shannah** [comment]
After looking at this a bit more, I think the Generations technique is leading you astray.  It looks like the "Growth" figure refers to new memory allocated/objects created since the last generation.  However, it doesn't take into account any released memory.  You can see this clearly when you look at the 128KB GFX Texture Level allocations that are allocated in each generation.  These are the result of creating a texture with the text to display.

This makes it look like the number of allocated GFX Texture Level objects is growing without bound.  But if you change to Statistics View and look at the row for GFX Texture Level, and then click the button several times, you'll see that the number of persistent objects stays constant at 106 and memory at 13.20 MB.  This is consistent with the fact that we use a LRU cache for the textures.  When a new one is created, it is added to the cache, but the another one is removed at the same time.

In playing with the app for quite a while, I do see an upward trend over time... but then from time to time the memory usage goes down resulting in a relatively constant memory footprint.

**Comment by jackyy415** [comment]
If there is no leak, why commenting the codes for updating textarea will make the memory usage stable and prevent my app from crashing?

**Comment by shannah** [comment]
OK.  I think I have found where there might be a problem.  We cache string
widths and it doesn't look like it ever gets cleaned out.  I'll convert it
into an LRU cache and commit that shortly.


On Tue, Sep 29, 2015 at 8:29 AM, jackyy415 <notifications@github.com> wrote:

> If there is no leak, why commenting the codes for updating textarea will
> make the memory usage stable and prevent my app from crashing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-144094691>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Hi,

Great for finding it out. The instrument shows similar issue as well. Thanks a lot.

Best Regards,
Jacky Yuen

**Comment by shannah** [comment]
OK.  This patch should fix the issue.
https://github.com/codenameone/CodenameOne/commit/7e19d38e28e4da6a928e44fc41b2f23014c0b284

**Comment by jackyy415** [comment]
Cool and thanks. We will try it tomorrow. The fix is available on the build server now, right?

**Comment by shannah** [comment]
It isn't on the server yet.  I assume Shai will post it as soon as he gets
a chance.

On Tue, Sep 29, 2015 at 9:05 AM, jackyy415 <notifications@github.com> wrote:

> Cool and thanks. We will try it tomorrow. The fix is available on the
> build server now, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-144104645>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Ok, thanks for the great work. We can't wait to try it.

**Comment by jackyy415** [comment]
Hi,

Can you please update us when the fix is available on the build server?
Btw, is there any way to inform users whenever there is any update on the build server?

Thanks.

Best Regards,
Jacky Yuen

**Comment by jackyy415** [comment]
Hi,

Is the fix available on the build server now?

Thanks.

**Comment by codenameone** [comment]
Yes, it should be up.

**Comment by jackyy415** [comment]
Hi,

Thanks. Last question, we are using the pro account, will this fix apply to our build if we choose the build version as 3.1?

Thanks.

**Comment by codenameone** [comment]
No.

**Comment by jackyy415** [comment]
Hi,

I've tried the fix with the latest build. It does solve the stringWidth problem but the memory issues with [DrawImage execute] and [DrawString execute] are still there.

Calling [DrawImage execute] allocated 1MB and calling [DrawString execute] allocated 256KB. Both responsible caller pointed to glsmLoadTextureLevelBuffer.

If these two issues are solved, the memory issue should be resolved finally.

Thanks.

**Comment by shannah** [comment]
These allocations are normal.  That doesn't indicate a leak.

**Comment by jackyy415** [comment]
Hi,

I've noticed that these allocations happened when I update TextArea each time and the memory is not released. What if I've tried to update the TextArea for thousand times? It looks like it will allocated 1MB for thousand times.

Thanks.

**Comment by shannah** [comment]
We keep a texture cache.  It will increase until the cache if full, then it
will remain stable as the oldest one will be removed when a new one is
added.

**Comment by jackyy415** [comment]
Hi,

Do you mean the allocated memory is used by the cache?

If yes, I have just tried to play around with the DrawString.m. If the allocated is held by the cache, commenting the codes about caching should get rid of the problem. I have commented the following line: [DrawStringTextureCache cache:str f:font t:textureNaem c:color a:255];
After commenting it, the memory goes up even faster than before. I think the codes to create the texture is the root cause of the memory problem. Enabling cache just reduces the no.of times to create the texture and thus the memory goes up slowly. By disabling the cache, it just amplifies the memory issue that the memory cannot be released.

**Comment by jackyy415** [comment]
The following method in DrawImage.m retain the obj "img" such that it's reference count is 2. Later, when the GLUIImage release method is called, the reference count becomes 1 only such that the object "img" dealloc cannot be called and thus glDeleteTextures is not called.

-(id)initWithArgs:(int)a xpos:(int)xpos ypos:(int)ypos i:(GLUIImage*)i w:(int)w h:(int)h

**Comment by shannah** [comment]
The "img" should outlive the DrawImage instance as the actual CN1 java
"Image" instance will also be holding a reference to it.

On Mon, Oct 5, 2015 at 3:38 AM, jackyy415 <notifications@github.com> wrote:

> The following method in DrawImage.m retain the obj "img" such that it's
> reference count is 2. Later, when the GLUIImage release method is called,
> the reference count becomes 1 only such that the object "img" dealloc
> cannot be called and thus glDeleteTextures is not called.
>
> -(id)initWithArgs:(int)a xpos:(int)xpos ypos:(int)ypos i:(GLUIImage*)i
> w:(int)w h:(int)h
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-145491919>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Ok, so when will the CN1 java "Image" instance release it such that the dealloc can be called and thus called glDeleteTextures?

In my case, it looks like the java "Image" instance is not released.

**Comment by shannah** [comment]
It will be released when the object is garbage collected.  This happens
when there are no more active references to the object in Java.
Is your program still crashing due to memory overload?  What metrics are
you using to suggest that there is a leak?  As I showed before the
"Generation marker" approach is flawed.

Steve

On Mon, Oct 5, 2015 at 9:03 AM, jackyy415 <notifications@github.com> wrote:

> Ok, so when will the CN1 java "Image" instance release it such that the
> dealloc can be called and thus called glDeleteTextures?
>
> In my case, it looks like the java "Image" instance is not released.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-145582741>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
My application is still crashing due to memory overload.

I suggest this is a leak because of the evidence from instrument tools. Both persistent bytes allocations and generation marker shows the DrawImage.m allocated 1MB in [DrawImage execute]. 

I disagree that the "Generation marker" approach is flawed. The memory usage will drop in each generation if the memory is really released. For iOS developers, it is the best tool for identifying memory leak or incorrect memory usage.
The reported stringwidth cache issue is identified by the mark generation and it also proves your fix is working. Furthermore, it also makes me believe the DrawString cache works fine as the memory usage does drop down after the cache is cleared.

However, I have no idea to free the 1MB memory allocated during DrawImage. How can I clear the reference to the image at the Java side? We used image for showing the progress status. Actually, we used one image for every 1% so we used 100 images for showing 1-100%. We use fetchResource to get the image and set the image via setIcon. How do I clear the image reference after setting the image as icon?

Thanks.

**Comment by shannah** [comment]
A couple of points:

1.  Looking back at your earlier comment:

"If yes, I have just tried to play around with the DrawString.m. If the
allocated is held by the cache, commenting the codes about caching should
get rid of the problem. I have commented the following line:
[DrawStringTextureCache cache:str f:font t:textureNaem c:color a:255];"

I just looked at the code, and making this change will cause a memory leak,
since the texture is destroyed when it is removed from the cache.  If you
prevent the texture from being added to the cache, then the texture will
never be destroyed.  Hence your fix *caused* a big memory leak.

2.  RE: "How can I clear the reference to the image on the Java side?"
 When there are no more active references to the image.  If you're not
keeping a reference to the image, then it will be cleared in the next GC
cycle.

3. I can't comment on any of your other findings without a test case.

Steve

**Comment by jackyy415** [comment]
Hi,

After days of debugging, I still cannot resolve the app crash problem. The app works very fine in Android but it always crash in iOS.

I've tried to use the instrument tools to debug the memory usage, over 100MB are used by the [DrawImage execute]. Basically, my app just update the image to show the latest upload progress. 
I have a connection request which upload files and the app will sent an action event to the progress listener. The progress listener will update the progress image once it receives the event.

I am pretty sure this is the root cause as commenting the codes about updating progress image will solve the memory issue. As the app will update the same image for many times and the whole progress will last for several hours, I guess this is why the image cannot be released?

**Comment by shannah** [comment]
Please send me the project so I can take a look.

On Wed, Oct 7, 2015 at 8:26 AM, jackyy415 <notifications@github.com> wrote:

> Hi,
>
> After days of debugging, I still cannot resolve the app crash problem. The
> app works very fine in Android but it always crash in iOS.
>
> I've tried to use the instrument tools to debug the memory usage, over
> 100MB are used by the [DrawImage execute]. Basically, my app just update
> the image to show the latest upload progress.
> I have a connection request which upload files and the app will sent an
> action event to the progress listener. The progress listener will update
> the progress image once it receives the event.
>
> I am pretty sure this is the root cause as commenting the codes about
> updating progress image will solve the memory issue. As the app will update
> the same image for many times and the whole progress will last for several
> hours, I guess this is why the image cannot be released?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146230282>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
I cannot reproduce it in a simple project. I can reproduce it only in my app which is a large project.

**Comment by shannah** [comment]
Anything you can provide me with would be better than I have now.  E.g.

1. Java source code in the area that you suspect is causing the leak.
2. Smaller test cases if you can produce something smaller.
3. The full CN1 Netbeans project - and instructions on how to reproduce
4. The generated Xcode project - and instructions on how to reproduce
5. Screenshots from instruments that might help to demonstrate the leak.
6. Save an instruments project after running it and send it to me  (not
sure if that will work but worth a shot).

Steve

On Wed, Oct 7, 2015 at 10:19 AM, jackyy415 <notifications@github.com> wrote:

> I cannot reproduce it in a simple project. I can reproduce it only in my
> app which is a large project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146267649>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
The following screenshot from instrument shows the memory issue that we are having.

![leak](https://cloud.githubusercontent.com/assets/13036432/10363405/ee238d48-6de6-11e5-9eb5-bd1d381583c4.JPG)

**Comment by jackyy415** [comment]
I noticed that there are many 1MB allocations for calling [DrawImage execute]. However, we don't have any image with size 1MB. It looks like it is trying to draw the frame instead of setting image.

**Comment by shannah** [comment]
That allocation is likely for the texture, which won't be compressed, so
think in terms of 4 bytes per pixel.  so a 1000x1000 image would be 4
megs.  That math may not be exact (i.e. it may have some optimizations),
but I think that would explain the size of the allocation.

On Thu, Oct 8, 2015 at 9:45 AM, jackyy415 <notifications@github.com> wrote:

> I noticed that there are many 1MB allocations for calling [DrawImage
> execute]. However, we don't have any image with size 1MB. It looks like it
> is trying to draw the frame instead of setting image.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146617377>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Hi,

Thanks for the explanation. As you can see, my app is full of 1MB memory allocation and the stacktrace for each allocation is more or less the same.

**Comment by shannah** [comment]
Are you still commenting out the caching?  After the cache is full, these
allocations will be balanced out by deallocation of the oldest texture....
So it will be net zero.

On Thu, Oct 8, 2015 at 9:53 AM, jackyy415 <notifications@github.com> wrote:

> Hi,
>
> Thanks for the explanation. As you can see, my app is full of 1MB memory
> allocation and the stacktrace for each allocation is more or less the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146620264>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
No, the caching has not been commented out. 

What is the class for caching image? I can find the class for caching string only. 

Besides, is it possible to reduce the cache size / turn off the cache? The caching for the image consumed 100MB already. I don't think mobile platform need such large caching.

**Comment by shannah** [comment]
On Thu, Oct 8, 2015 at 10:34 AM, jackyy415 <notifications@github.com> wrote:

> No, the caching has not been commented out.
>
> What is the class for caching image? I can find the class for caching
> string only.
>

GLUIImage.m  getTexture



> Besides, is it possible to reduce the cache size / turn off the cache? The
> caching for the image consumed 100MB already. I don't think mobile platform
> need such large caching.
>
Actually, in looking at the code for the image textures, it doesn't use a
cache.  It just deletes it when the GLUIimage is deallocated - which should
happen when the Java image is gc'd.

There may be something we can do to destroy these textures before the GC
happens, but I'm interested to see this case before making such a change as
there may be some things we can do on the Java side to prevent such a
memory overload.  If you think that the problem is with your progress
dialog using 100 different images, can you produce an isolated test case
with this so I can test with it?

Steve


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146632512>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Hi,

I have tried to reproduce it but I can't......
However, just commenting label.setIcon() does solve the issue.

If there is no caching, I guess the memory will increase continuously until the image can be deallocated. However, we cannot figure out how to dealloc it. 
We tried the following ways but nothing works:
1) setIcon(null)  before updating the label
2) getIcon() to get the image and set the image to null

By setting the image to null, we think the image should be deallocated but it does not.

**Comment by shannah** [comment]
If you comment that out, it just means that it may never create the texture
in the first place.  The image is still retained in memory on the Java side
somewhere probably.

I'll try to add some code to clear out textures when a memory warning is
received.  A test case would still be really helpful here, but I do see a
some low-hanging fruit here.

All that aside, you'll probably still want to identify where you are
storing references to these images in Java code as even if I clear out
textures, your image will still be present on the Java side of things if
you don't remove references.

Steve

On Fri, Oct 9, 2015 at 8:59 AM, jackyy415 <notifications@github.com> wrote:

> Hi,
>
> I have tried to reproduce it but I can't......
> However, just commenting label.setIcon() does solve the issue.
>
> If there is no caching, I guess the memory will increase continuously
> until the image can be deallocated. However, we cannot figure out how to
> dealloc it.
> We tried the following ways but nothing works:
> 1) setIcon(null) before updating the label
> 2) getIcon() to get the image and set the image to null
>
> By setting the image to null, we think the image should be deallocated but
> it does not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146911026>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by shannah** [comment]
I have just pushed a change that will cause all of these textures to be deleted when a memory warning is received.  This should fix your crashes.
https://github.com/codenameone/CodenameOne/commit/690a0d90fd8f9957e0df45bf2e879218f3619a2f

It isn't on the build server yet, but should be soon  (Check with Shai on that).

I would still look into your Java code and see why you are retaining references to all of these images even after you're done with them.

**Comment by shannah** [comment]
After thinking about this some more, we are thinking about reverting this
patch since it fixes a problem that has not been demonstrated to exist.

You can try to apply the patches locally in your source and see if it fixes
the issue, but frankly, even if it does fix your issue, I think the issue
could have been solved on the Java side.  E.g. Can you share the loop that
you are using to perform the animation so I can take a look?

On Fri, Oct 9, 2015 at 9:59 AM, Steve Hannah <steve@weblite.ca> wrote:

> If you comment that out, it just means that it may never create the
> texture in the first place.  The image is still retained in memory on the
> Java side somewhere probably.
>
> I'll try to add some code to clear out textures when a memory warning is
> received.  A test case would still be really helpful here, but I do see a
> some low-hanging fruit here.
>
> All that aside, you'll probably still want to identify where you are
> storing references to these images in Java code as even if I clear out
> textures, your image will still be present on the Java side of things if
> you don't remove references.
>
> Steve
>
> On Fri, Oct 9, 2015 at 8:59 AM, jackyy415 <notifications@github.com>
> wrote:
>
>> Hi,
>>
>> I have tried to reproduce it but I can't......
>> However, just commenting label.setIcon() does solve the issue.
>>
>> If there is no caching, I guess the memory will increase continuously
>> until the image can be deallocated. However, we cannot figure out how to
>> dealloc it.
>> We tried the following ways but nothing works:
>> 1) setIcon(null) before updating the label
>> 2) getIcon() to get the image and set the image to null
>>
>> By setting the image to null, we think the image should be deallocated
>> but it does not.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-146911026>
>> .
>>
>
>
>
> --
> Steve Hannah
> Web Lite Solutions Corp.
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by shannah** [comment]
I have reverted the change in our master now.  You can still see the patch here: 
https://github.com/codenameone/CodenameOne/commit/690a0d90fd8f9957e0df45bf2e879218f3619a2f

I don't recommend using this patch though.  After discussing with Shai, I think the best thing for you to do is fix your leak in your Java code.  When you are finished with the image, try calling dispose() on the image.  That will remove the image from memory.

**Comment by jackyy415** [comment]
Hi, 

We have tested the changes locally. The memory will be released only when we trigger the memory warning.

However, this one not the behavior we want. We expect the image will be released once we've updated the label with another image.

Btw, we have tried to use dispose on the image but it does not work as well. The memory still cannot be released after setting with another new image.

We are really out of idea on what is going on. If there is leak in our java codes, why it works fine in Android version?

Thanks.

**Comment by shannah** [comment]
I won't be doing anything more on this issue until I receive a test case.

On Sat, Oct 10, 2015 at 8:15 AM, jackyy415 <notifications@github.com> wrote:

> Hi,
>
> We have tested the changes locally. The memory will be released only when
> we trigger the memory warning.
>
> However, this one not the behavior we want. We expect the image will be
> released once we've updated the label with another image.
>
> Btw, we have tried to use dispose on the image but it does not work as
> well. The memory still cannot be released after setting with another new
> image.
>
> We are really out of idea on what is going on. If there is leak in our
> java codes, why it works fine in Android version?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147096882>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Hi,

It looks like I have reproduced the image memory issue. Can you please download the Java/iOS project and check it?

Basically, the label will be updated with new images for 10 times and the interval for each update is 5 seconds. 
When the label has been updated for 10 times, a dialog will be shown to indicate the testing is completed.

When you use the instrument tools to track the memory, you can see some 1MB entries are allocated by [DrawImage execute] and the memory will not be released even the testing is completed. They will be released only when the memory warning is triggered.

In this test case, the 1MB entry is appeared for 2-3 times only as it updated the label img for 10 times only. In our real application, more 1MB memory are allocated and caused impact to our app and crashed finally. 

Java Project: 
https://drive.google.com/file/d/0B3VEmM6wQ_-Ic3dISjRkWmFHUkE/view?usp=sharing

iOS Project: 
https://drive.google.com/file/d/0B3VEmM6wQ_-IRmVTaGVFbGNhWkU/view?usp=sharing

**Comment by shannah** [comment]
Haven't looked at it yet, but your description sounds like this is normal
operation.  The memory warning will trigger a GC cycle which will free the
memory.   If it is deleted from a memory warning then this should be fine.
 @CodenameOne, what do you think?

On Sun, Oct 11, 2015 at 10:39 AM, jackyy415 <notifications@github.com>
wrote:

> Hi,
>
> It looks like I have reproduced the image memory issue. Can you please
> download the Java/iOS project and check it?
>
> Basically, the label will be updated with new images for 10 times and the
> interval for each update is 5 seconds.
> When the label has been updated for 10 times, a dialog will be shown to
> indicate the testing is completed.
>
> When you use the instrument tools to track the memory, you can see some
> 1MB entries are allocated by [DrawImage execute] and the memory will not be
> released even the testing is completed. They will be released only when the
> memory warning is triggered.
>
> In this test case, the 1MB entry is appeared for 2-3 times only as it
> updated the label img for 10 times only. In our real application, more 1MB
> memory are allocated and caused impact to our app and crashed finally.
>
> Java Project:
>
> https://drive.google.com/file/d/0B3VEmM6wQ_-Ic3dISjRkWmFHUkE/view?usp=sharing
>
> iOS Project:
>
> https://drive.google.com/file/d/0B3VEmM6wQ_-IRmVTaGVFbGNhWkU/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147223782>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
We expect that the memory will be deallocated once the label is updated with another image. Besides, it is not a good approach that the memory will be released only when there is memory warning.

**Comment by shannah** [comment]
That is not the right expectation in a garbage collected environment.
Memory will be released when the GC decides it should be released.  When
you set the icon to "null", assuming that you have no other reachable
references to the image, it will be marked for deletion in the next GC
cycle.  GC cycles are triggered by a number of mechanisms using heuristics
to balance performance, power consumption, and memory needs.  One *hard*
trigger is a memory warning.

You can also trigger gc cycles yourself using System.gc(), but this isn't
generally recommended.

On Sun, Oct 11, 2015 at 10:46 AM, jackyy415 <notifications@github.com>
wrote:

> We expect that the memory will be deallocated once the label is updated
> with another image. Besides, it is not a good approach that the memory will
> be released only when there is memory warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147225901>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
We have tried to use System.gc() but the memory does not clean up.

**Comment by shannah** [comment]
Probably you still have references to the image then.  If you call
dispose() on the image, and then System.gc(), the image should be cleared
in the next GC cycle.  If not, then produce a test case for me where you do
this and it doesn't free the image in the next cycle.

On Sun, Oct 11, 2015 at 10:52 AM, jackyy415 <notifications@github.com>
wrote:

> We have tried to use System.gc() but the memory does not clean up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147229027>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Hi,

I've updated the codes and it shows that the memory is not freed even after calling dispose() and then System.gc().

Java Project: 
https://drive.google.com/file/d/0B3VEmM6wQ_-Ib21PR3d5a0FWRFU/view?usp=sharing

iOS Project: 
https://drive.google.com/file/d/0B3VEmM6wQ_-IaTBCU2lkNENFelk/view?usp=sharing

Thanks.

**Comment by codenameone** [comment]
@shannah is on holiday today (Canadian Thanksgiving) but in regard to the comments here I'd like to clarify a couple of things.

Setting a variable to null does nothing. GC runs periodically and as needed. A GC process has to walk a rather large object graph which is CPU intensive and for performance you want to minimize this to only when necessary. Moreso on devices where battery life is crucial and reducing CPU usage is critical.

Images are comprised of the Java and the native portion and this balance creates a unique state where the initial GC needs to also invoke the finalizer to clear the native portion which isn't trivial.

If you are seeing a leak with images I suggest you post the code you use to create the image. Also check for EDT violations which can happen with mutable images.

**Comment by jackyy415** [comment]
Hi,

The following codes create the label and update the label image whenever the ActionListener receives action event.

	public class StateMachine extends StateMachineBase {
		private int counter = 0 ;
		public StateMachine(String resFile) {
			super(resFile);
			// do not modify, write code in initVars and initialize class members there,
			// the constructor might be invoked too late due to race conditions that might occur
		}

		/**
		 * this method should be used to initialize variables instead of
		 * the constructor/class scope to avoid race conditions
		 */
		protected void initVars(Resources res) {

		}

		@Override
		protected void onMain_TestLabel2Action(final Component c, ActionEvent event) {
			final Container container = new Container(new LayeredLayout());

			final Label imgLabel = new Label("");
			imgLabel.setAlignment(Component.CENTER);
			container.addComponent(imgLabel);

			Display.getInstance().getCurrent().addComponent(container);

			final ActionListener progressListener = new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent evt) {
					Image img = imgLabel.getIcon();
					if (img != null) {
						img.dispose();
					}
					System.gc();
					if (counter % 10 == 0) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading.png"));
					} else if (counter % 10 == 1) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading2.png"));
					} else if (counter % 10 == 2) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading3.png"));
					} else if (counter % 10 == 3) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading4.png"));
					} else if (counter % 10 == 4) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading5.png"));
					} else if (counter % 10 == 5) {
						imgLabel.setIcon(fetchResourceFile().getImage("loading6.png"));
					} else {
						imgLabel.setIcon(fetchResourceFile().getImage("loading.png"));
					}
					Display.getInstance().getCurrent().animateLayoutAndWait(0);
					counter++;


				}
			};


			Display.getInstance().invokeAndBlock(new Runnable() {
				@Override
				public void run() {
					for (int i = 0; i < 10; i++) {
						progressListener.actionPerformed(new ActionEvent(this));
						try {
							Thread.sleep(5000);
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
					}

				}
			});

			Dialog.show("Completed", "Testing is completed.", "OK", null);

		}
	}

**Comment by shannah** [comment]
You have an EDT violation in this code.  You are calling actionPerformed()
inside invokeAndBlock() which will run off the EDT.

On Mon, Oct 12, 2015 at 8:37 AM, jackyy415 <notifications@github.com> wrote:

> Hi,
>
> The following codes create the label and update the label image whenever
> the ActionListener receives action event.
>
> public class StateMachine extends StateMachineBase {
>     private int counter = 0 ;
>     public StateMachine(String resFile) {
>         super(resFile);
>         // do not modify, write code in initVars and initialize class members there,
>         // the constructor might be invoked too late due to race conditions that might occur
>     }
>
>     /**
>      * this method should be used to initialize variables instead of
>      * the constructor/class scope to avoid race conditions
>      */
>     protected void initVars(Resources res) {
>
>     }
>
>     @Override
>     protected void onMain_TestLabel2Action(final Component c, ActionEvent event) {
>         final Container container = new Container(new LayeredLayout());
>
>         final Label imgLabel = new Label("");
>         imgLabel.setAlignment(Component.CENTER);
>         container.addComponent(imgLabel);
>
>         Display.getInstance().getCurrent().addComponent(container);
>
>         final ActionListener progressListener = new ActionListener() {
>             @Override
>             public void actionPerformed(ActionEvent evt) {
>                 Image img = imgLabel.getIcon();
>                 if (img != null) {
>                     img.dispose();
>                 }
>                 System.gc();
>                 if (counter % 10 == 0) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading.png"));
>                 } else if (counter % 10 == 1) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading2.png"));
>                 } else if (counter % 10 == 2) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading3.png"));
>                 } else if (counter % 10 == 3) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading4.png"));
>                 } else if (counter % 10 == 4) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading5.png"));
>                 } else if (counter % 10 == 5) {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading6.png"));
>                 } else {
>                     imgLabel.setIcon(fetchResourceFile().getImage("loading.png"));
>                 }
>                 Display.getInstance().getCurrent().animateLayoutAndWait(0);
>                 counter++;
>
>
>             }
>         };
>
>
>         Display.getInstance().invokeAndBlock(new Runnable() {
>             @Override
>             public void run() {
>                 for (int i = 0; i < 10; i++) {
>                     progressListener.actionPerformed(new ActionEvent(this));
>                     try {
>                         Thread.sleep(5000);
>                     } catch (InterruptedException e) {
>                         e.printStackTrace();
>                     }
>                 }
>
>             }
>         });
>
>         Dialog.show("Completed", "Testing is completed.", "OK", null);
>
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147440621>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Do you mean that's why the image cannot be released?

If yes, what should I do if I have a long running process which do not want to block the UI?

**Comment by shannah** [comment]
It means that behaviour in this test is undefined since you are accessing
the UI off the EDT.   All kinds of weird things may happen.

Wrap your progressListener.actionPerformed() call inside
Display.callSerially()

Steve

On Mon, Oct 12, 2015 at 8:54 AM, jackyy415 <notifications@github.com> wrote:

> Do you mean that's why the image cannot be released?
>
> If yes, what should I do if I have a long running process which do not
> want to block the UI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147445057>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Oh....as I remember, some docs mentioned that the action listener happens on the EDT...or it means other things?

**Comment by shannah** [comment]
But you are calling the actionPerfomed() directly.  So it happens in
whatever Thread you are on when you call it.

But the contract is that it should *only* be called on the EDT.

On Mon, Oct 12, 2015 at 8:58 AM, jackyy415 <notifications@github.com> wrote:

> Oh....as I remember, some docs mentioned that the action listener happens
> on the EDT...or it means other things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-147445812>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
Just tried to update the codes by wrapping your progressListener.actionPerformed() call inside
Display.callSerially(), the 1MB is still not cleaned up after waiting for a long time. So is triggering the memory warning is the only way to release the memory? dispose() and System.gc() do not clean up the memory as well....

**Comment by codenameone** [comment]
The EDT comment was related to mutable images.
What you are doing here is remove the resources file then recreate it with all the images within it (theme etc.) over and over again (hence 1mb). This has nothing to do with the individual image and everything to do with you reloading the resources object over and over.

Just keep a reference to the image object instead of calling fetchResources repeatedly. I would also suggest using: `setKeepResourcesInRam(true)`

**Comment by codenameone** [comment]
Just to clarify, the System.gc() deletes the weak reference to the theme resource file.

**Comment by jackyy415** [comment]
Hi,

Thanks for the advice. Actually I was keeping the image reference by using an array before as below:
imgArray[0] = fetchResourceFile().getImage("loading.png");
imgArray[1] = fetchResourceFile().getImage("loading2.png");
....

However, the memory problem still exists and I thought coding in this way keeps the image references in the code and thus we changed to use fetchResourceFile().getImage(<img name>) whenever we need it.

**Comment by jackyy415** [comment]
Btw, which exact code remove the resources file then recreate it with all the images within it (theme etc.)? fetchResourceFile()?

**Comment by jackyy415** [comment]
By setting setKeepResourcesInRam(true) in initVar(), the 1MB are still allocated by [DrawImage execute] for three times. If it is loading the resources, I expect 1MB resources will be loaded for the first time only as the resources are cached in ram. Am I having the wrong expectation?

**Comment by jackyy415** [comment]
Hi,

In order to confirm the root cause of the problem, we have tried to get the image only but not setting it to label. There is no 1MB memory allocation problem. It looks like the 1MB memory problem is actually allocated by the label.setImage().

Thanks.

Best Regards,
Jacky Yuen

**Comment by shannah** [comment]
The 1MB allocation is for an OpenGL texture.  It is only created when the image is drawn.  It is deleted when the image is deallocated.   Resources objects keep references to all Images in them.  Therefore, images won't be garbage collected until the Resource file itself is garbage collected - and thus, the texture won't be deleted until this happens.

It is true that if you keep a reference to the resource file for the duration of the app, or you use setKeepResourcesInRam(true), the textures won't be deleted.   We are discussing how we want to handle this.  For your case, you are best to either load the images from a resource file that you can discard when you are done - or just include them in the source bundle and load them with Display.getResourceAsStream()

**Comment by shannah** [comment]
Sorry.. in looking further, my analysis is incorrect.  The actual reference is weak so it will be removed when there is a memory warning.  So you should be fine just loading the images from a Resources file.

**Comment by jackyy415** [comment]
Hi,

Thanks for the analysis. If the reference is weak, System.gc() should free the memory but it turns out the memory is still here after calling System.gc().

**Comment by shannah** [comment]
The weak reference implementation on ios waits until a memory warning to
clear the weak references.

**Comment by jackyy415** [comment]
The conclusion is the memory will be released only when there is memory warning, right?

**Comment by codenameone** [comment]
That's how weak references work best. Otherwise caching will break.
Notice that you should also be aware of memory usage e.g. by keeping the resources correctly and not re-allocating images which can create duplicates in RAM. 
We try to make it as "seamless" as possible but with every abstraction there are complexities that get introduced.

**Comment by jackyy415** [comment]
OK, that sounds my issue cannot be resolved and my app will keep crashing....

**Comment by shannah** [comment]
If your app is crashing, this is not the reason.  The memory is cleared
when there is a memory warning.  That will prevent an app crash.

You're looking in the wrong places.

On Wed, Oct 14, 2015 at 9:02 AM, jackyy415 <notifications@github.com> wrote:

> OK, that sounds my issue cannot be resolved and my app will keep
> crashing....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1577#issuecomment-148099385>
> .
>



-- 
Steve Hannah
Web Lite Solutions Corp.

**Comment by jackyy415** [comment]
The app crashed after receiving several memory warnings and using instruments showed that the admob, image and string used most of the memory (i.e. > 100mb)

**Comment by shannah** [comment]
Even when you call Image.dispose() after you're finished with an image?

**Comment by codenameone** [comment]
Currently `Image.dispose()` doesn't fully dispose the image since weak references are kept. This is something we can fix relatively easily to properly dispose on iOS which should reduce the image RAM usage.
What is more interesting to me is that you say that `String's` take up a lot of the RAM. String's in Java can be interned which means there might be a memory leak if you use a VERY large amount of Strings. Can you provide more information on that?

**Comment by jackyy415** [comment]
Hi,

Is the fix on the StringWidth available on build version 3.2?

Thanks.

**Comment by jackyy415** [comment]
Hi,

The String takes up a lot of RAM because of the mentioned problem in this issue. The cache of the string increases without boundary. After Codename one fixes it, the memory used by the String is limited (though it still occupies around 20MB as the cache size is 100).

As you have mentioned that the fix on properly dispose on iOS is easy, can you please fix it?

Thanks.

**Comment by jackyy415** [comment]
Hi, 

Is there any update? Is this included in Codename One v3.2?

**Comment by codenameone** [comment]
@shannah did we do something about dispose() removing the weak references?

If not I'll take a look.

**Comment by shannah** [comment]
When I went and looked, dispose() already removes the native peer, which would cause the texture to be deleted.  That is the crux of this complaint so I don't think there's anything to do here.

**Comment by codenameone** [comment]
I thought we also mentioned that there is a weak reference to the image somewhere which can pile up in the weak reference hash map and that dispose() should remove it?
If you don't recall I'll just search thru our email logs and follow up.

**Comment by shannah** [comment]
Yes that's true.  But upon thinking about it, I don't think that would make a dent in this issue, unless -- correct me here if I'm wrong about the way it works:

When the resource file is loaded, all of the images it contains are loaded into RAM.  It will remain in RAM until the Resource file is GC'd.  But the memory footprint should remain constant.

I.e.

Calling theme.getImage("someimage.png") shouldn't have any effect on memory.   Am I right?

The memory problem here was caused when an image is actually rendered to the screen.  This is because during rendering, it generates the OGL texture which is quite large, especially on hi-res devices - and the OGL texture won't be deleted until the GLUIImage is released - which happens either when the Image is disposed or GC'd. 

So the fact that dispose() calls "releaseImage(peer)" - i.e. releases the peer GLUIImage means that it will free up this texture memory - and the RAM will again return to the usage level when the Resource file was initially loaded.

Am I missing something?

**Comment by codenameone** [comment]
@shannah Thanks. Not sure.

@jackyy415 what is the actual application status? Is it crashing?

**Comment by jackyy415** [comment]
@codenameone 
The actual application will crash after running for a long time, say few hours. The image will be updated for many times during few hours.

**Comment by codenameone** [comment]
What sort of app do you have that's running for so long?
Is it in the foreground for that amount of time? If not then its likely killed by the watchdog process.

**Comment by jackyy415** [comment]
It is a backup app running in the foreground so it won't be killed by watchdog.

**Comment by codenameone** [comment]
Can you accelerate that crash in a test case?

**Comment by shannah** [comment]
Closing this issue as it's been dead for a while.
