### ISSUE TITLE
New Animation Manager breaks Poker and Solitaire demos

### ISSUE THREAD

**Issue by jjvanhorssen** [codenameone/CodenameOne#1640]
The new Animation Manager (december 2015) breaks animation compatibility. The Poker and Solitaire demos (and my app) no longer work properly. 

Also, the Developer Guide (version 2016-01-13), chapter/appendix Casual Game Programming, needs updating since it lists a CN1Poker version that doesn't properly work on an Android device: the dealing cards animation shows the cards mostly jumping and only sometimes sliding to their positions.

CN1 version: plugin 3.2.6, libs 2016-01-11.

Solitaire: in the Simulator, the layout and animations work mostly fine but on my iOS and Android devices there are a lot of problems.

Simulator (Windows 7, NetBeans 8.0.2): 
- I replaced the font icons by text since they are missing. 
- But how to access the hamburger menu? I don't see the 3 dots and there is even no space for it. 
- Sometimes it is possible to drags a groups of cards with some downfacing cards taken; while dragged they are temporarily flipped facing up. 
- Autoplay doesn't always seem to work. (Not all moves are played.)

On iOS 9.2 (iPad 4), iOS 8.4 (iPhone 4): 
- [?] is shown in the hamburger menu check boxes. 
- After startup, the tableau background card-backs jump to the bottom of the container/screen. 
- Sometimes, in the deal-from-deck animation, cards in the rightmost tableau are temporarily facing up, and cards already facing up are flipped facing down. The final deal-state is correct, however. 
- Undo/Redo: sometimes results in a facing-up card on deck 0 and a facing-down on deck 1. 
- Redo sometimes 'jumps' to the new layout instead of animating. 
iPhone only: 
- A sequence of autoplay moves left an inconsistent foundation state: top cards heart-J, club-10, club-K, diamond-Q; i.e., 2 club-cards on different foundation stacks.

On Android 5.1.1 (Nexus 7) there are more problems. 
- The deal-from-deck animation is not a pretty sight. Cards are inserted (slide to) at the bottom of the tableau stacks, so they slide under the other cards. The moving cards should be facing down but are usually facing up, always showing the first card dealt to tableau 1. The cards in rightmost tableau are temporarily facing up. Finally, cards already facing up are flipped facing down and back again. The final deal-state is correct, however. 
- Autoplay is also not correct when there are several moves in a row. During the animations, several foundation cards facing up change their card value (front) temporarily. Also the moving cards slide under the foundation card (and sometimes over, but this is the exception). 
- After finishing the game, the well-done screen is corrupted since the text seems to be displayed not overlayed but below the cards (in a big white space), which are only partly visible in a tiny portion at the top of the screen. 
- Starting a new game often fails because deal-from-deck is not started; the screen shows a deck and four kings on the foundations with the tableau empty. When tapping the deck, a card is dealt and the well done sequence is show. Sometimes repeating this results in successfully starting a new game.

**Comment by jjvanhorssen** [comment]
The issue is two-fold:
1) synchronization of consecutive (one after the other) animations
2) Z-ordering during animation

**Comment by codenameone** [comment]
I just played a full round of solitaire against the latest git sources without a problem. A lot of the issues you describe seem to be application issues and one of them (the overflow button) is a regression that's already fixed in git.

You can try using the source or wait for the update later in the week.

**Comment by jjvanhorssen** [comment]
I'm not sure what you mean by 'application issues'. I assume you mean the latest git sources of Codename One itself and not the Solitaire sources. To be sure, I Just tried again with Solitaire from git and the latest plugin/libs. (Resolved the issues concerning missing font icons.) But the animation of dealing and autoplay still doesn't work (on an Android device). I will wait for the update later this week and try again.

**Comment by codenameone** [comment]
So is it only "on device"?

If you mentioned it before than I totally missed it. This is probably related to the Android pipeline work we are doing and has nothing to do with the animation framework. We'll take a look at that and try to figure out what happened there.

**Comment by jjvanhorssen** [comment]
Most issues occur on an Android device, but also in the Simulator and on iOS devices there are issues. Just retested on iOS device and in simulator (Solitaire git sources, animation durations * 10).
The animation and layout issues remain (see original 'issue').
E.g.:
Simulator:
1. the deal from deck animation sometimes goes wrong (try a few times): all goes well until the (second?) last card dealt, suddenly all facing-up cards are flipped down and later flipped back up.
2. redo sometimes jumps to new state instead of animating.
iPad 4/iOS 9.2:
1. and 2. see simulator. The deal from deck animation now almost always goes wrong.
3. a card sometimes slides under other cards instead of over it (z-ordering), I haven't seen this in the simulator (yet).

Is the new version coming this week going to fix this?

P.S. In the app store version, redo also jumps instead of animates. That aside, it works fine and is a great game.

**Comment by codenameone** [comment]
I'm not sure if the issues on the simulator are related but I did fix a major bug in the animation process that didn't properly flush the animation queue after an "andWait" call and thus returned an incorrect value for isAnimating(). This caused a cascading effect where all following add/remove calls became animations to avoid an exception and flickering became an issue. Should be fixed in the server and the release coming out today/tomorrow.

**Comment by jjvanhorssen** [comment]
Ah yes, now the animations in Solitaire-built-from-source work again (libs 2016-01-21). And also in my app. Both on iOS and Android devices. Z-ordering also works, I adapted the SolitaireLayout class to replace GridLayout. I'll update my question on StackOverflow. 

There are a few minor issues remaining with Solitaire (not in my app, so far).
iOS devices: tableau backgrounds at bottom of container, should be at top (see above screen print).
Android device: when a card starts moving, the card it will land on top of usually flashes, as if the button is pressed.
All versions including simulator: redo sometimes jumps to new state instead of animating.
