### ISSUE TITLE
bit shifts code incorrectly on IOS 32bit 

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2281]
Only on (obsolete) 32 bit platforms, bit shifts of the form (1<<n) are coded incorrectly
and produce values of zero for n>=32
Note that the attached test program has to be built with ios.debug.arch armv7 and run on
an old iphone.

````java
package dtest.boardspace;
//
// illustrates the IOS-only bit shift error
// issue 2277
// this is most likely an optimizer bug in xcode 7, apparently fixed in xcode 9
//
import java.util.Vector;

import com.codename1.ui.Component;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;


class DisplayPane extends Component 
{	
	String messages[] = {};
	DisplayPane(String m[]) 
	{ super(); 
	  messages =m; 
	}
	public Dimension getPreferredSize() 
	{ return(new Dimension(getParent().getWidth(),Math.max(500,messages.length+1)*40)); 
	}
	public void paint(Graphics g) 
	{	super.paint(g);
		int w = getWidth();
		int h = getHeight();
		g.clipRect(0, 0, w, h);
		g.setColor(0xffffff);
		g.fillRect(0, 0, w, h);
		int ypos = 20;
		for(String m : messages)
		{	g.setColor(0xff);
			g.fillRect(0,ypos,40,40);
			g.setColor(0);
			g.drawString(m, 40, ypos);
			ypos+= 40;
		}
	}
}

class Vtest 
{
    int ii = 0;
    // adding this line makes IOS builds fail
    //int jj = nextPlayer[ii];
    //
    
    // this version, using a default function, compiles but causes
    // a hard crash on IOS.
    //int jj = nextPlayer(ii);
    
	private Form current;
	private static Resources res;
	
	public void init(Object context) {
        try {
            res = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(res.getTheme(res.getThemeResourceNames()[0]));
        } catch (Exception e) {
            e.printStackTrace();
        }
 	}
	private long bitval(int n)
	{	  
		long mask = (1L<<n);
		return(mask);
	}
	public String[] doit()
	{	Vector<String>messages = new Vector<String>();
		{
		messages.addElement("Bitval 30 "+bitval(30));
		messages.addElement("Bitval 31 "+bitval(31));
		messages.addElement("Bitval 32 "+bitval(32));
		messages.addElement("Bitval 33 "+bitval(33));
		messages.addElement("Bitval 34 "+bitval(34));
		}

		String strs[]=new String[messages.size()];
		for(int i=0;i<messages.size();i++) { strs[i]=messages.elementAt(i); }
		return(strs);
	}
	
	public void start() {
		if (current != null) {
			current.show();
			return;
		}
		Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
		String m[] = doit();
		DisplayPane display = new DisplayPane(m);
		hi.addComponent("Center",display);
		//hi.addComponent("Center",new Label("fubar"));
		display.setVisible(true);
		display.repaint();
		hi.show();
		System.out.println("Dtest running");
	}

	public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public void destroy() {
	}

}

public class Dtest extends Vtest
{
	public void init(Object context) { super.init( context); }
	public void start() { super.start(); }
}

````
![img_0004](https://user-images.githubusercontent.com/5963076/32920086-e5c95830-cadc-11e7-957a-a1d4dd415e10.PNG)

**Comment by shannah** [comment]
"this is most likely an optimizer bug in xcode 7, apparently fixed in xcode 9"

Since we are switching to Xcode 9 default builds, I'm inclined to "not fix" this.  @codenameone let me know if you disagree, and I'll reopen.

**Comment by triplesub** [comment]
I hit this bug with the latest CodenameOne, so it hasn't been fixed by the switch to Xcode 9. The following code:

`        int shift = 48;`
`        Log.p(String.valueOf(1L << shift));`

Prints "0" to the log on a 32-bit iOS device.

**Comment by codenameone** [comment]
We'll have to dig up an old 32 bit device to verify this. 
@shannah do you have an old device or should I check this?

**Comment by ddyer0** [comment]
I verified that this still fails with a build done just now.

**Comment by shannah** [comment]
I have a graveyard of old iphones.  I'm sure at least one of them is 32 bit.
