### ISSUE TITLE
Switching from Box Y to Border Layout deletes Components in GUI Builder

### ISSUE THREAD

**Issue by seinecle** [codenameone/CodenameOne#2315]
(NetBeans plugin v. 3.8.1)

To reproduce:

- create an empty Form without autolayout.
- open it in the GUI Builder
- change the layout of the Form to Box Layout Y
- Add 5 Components in it (5 Labels for example).
- Changing the Form to Border Layout deletes (or puts out of view?) all Labels.

This does not happen in the reverse: a Form in Border Layout does not bug when we switch to Box Y Layout.

**Comment by codenameone** [comment]
We are considering removing the old non-autolayout mode. Can you elaborate on why you are using that instead of the auto-layout mode?

**Comment by seinecle** [comment]
The logic of drawing and resizing a Container is counterintuitive. If a Container is dropped directly in the Form, it should;
- occupy the space of the Component it contains if it's like a Box Y Layout, adjusted by its preferred size (like, takes all possible space on X axis for the Box Y Layout).
- or occupy the whole Form as for the Border Layout

This logic is lost when we are invited to draw the Container at the size we want. It creates the expectation that the Container will actually take up the space we've drawn, which is not the case as far as I can see.

But besides these issues of intepretations, the problems are the bugs. I did a random experiment and it bugs straight away. To reproduce:

- create Form through GUI with autolayout.
- place a Container in the Form, draw it to occupy the top half of the Form.
- give this Container a Border Layout
- drag and drop 5 Labels in this Container, each at a geographical position
- now, add a Button somewhere below the Container (not in it).

- save and run the preview from NetBeans, the result shows:

![image](https://user-images.githubusercontent.com/1244100/35192379-73e6b0ee-fe91-11e7-9c64-1e5d8a84e450.png)

In contrast, the classic layout / container system works just fine. I am finishing up a lesson on it, will post the url here shortly

**Comment by shannah** [comment]
I just followed your instructions with autolayout, and this is my result:

![image](https://user-images.githubusercontent.com/2677562/35195553-23ab52ae-fe7a-11e7-878e-0b461ff032f4.png)

There are a few fundamentals to understand about autolayout that will help.  Once you understand them, it should be quite easy to get the results you want.  In your case, I suspect that your insets were set incorrectly.  For this type of form, a few things to check.

1. Probably you don't intent for the form to be scrollable.  Make sure that the form's "Scrollable Y" and "Scrollable X" are unchecked.
2. For the BorderLayout, since you want it to occupy the top half, you want to make sure that the top, left, and right insets are fixed at 0mm.  (i.e. make sure the "lock" icon for those insets are hilighted... this should be automatic when you drag close enough).
3. For the bottom inset, make sure it is fixed at 50% (that will ensure it takes up half the height of the form).  If you just drag it, it should do this automatically, but you should check to be sure.
4. *Always* use the canvas "resize" tool to resize the canvas periodically and see how the components get resized.  If they don't resize as you expect, you may just need to adjust some of the insets.  By Canvas resize tool, I mean this icon 
![image](https://user-images.githubusercontent.com/2677562/35195609-01081de4-fe7b-11e7-9ee9-9e61ca6a6b9a.png)
in the bottom right corner of the canvas.  Just drag is around periodically.

**Comment by codenameone** [comment]
FYI we won't suddenly remove the old mode and will probably support it for the forseeable future but we might hide it a bit in the interface as we move forward. The way forward is the autolayout mode especially in your case I think it would be much easier to explain than the nuances of layout.

**Comment by seinecle** [comment]
Thanks for the detailed advice. I followed your instructions and still get an odd result, I must do something wrong:

- the preview:

FormAutoLayout
![image](https://user-images.githubusercontent.com/1244100/35196677-abccb0e6-fed5-11e7-98c1-d84da984d727.png)

- the GUI Builder:

![image](https://user-images.githubusercontent.com/1244100/35196680-bc8b29ee-fed5-11e7-82d7-6665e4fcbaeb.png)

**Comment by shannah** [comment]
Looks like the form is scrollable.  I'll look at improving the UI feedback when this is the case.  Make the form non-scrollable and you should see what your expected result.

**Comment by seinecle** [comment]
I think it isn't:

![image](https://user-images.githubusercontent.com/1244100/35196786-3470df02-fed7-11e7-982c-9c7606e20a68.png)

**Comment by seinecle** [comment]
I think it isn't:

![image](https://user-images.githubusercontent.com/1244100/35196804-79a92804-fed7-11e7-9bbb-970bc6642ae0.png)

**Comment by shannah** [comment]
Can you post the resulting Java and XML?

**Comment by seinecle** [comment]
Sure what's the best way to do it? Posting the class of my Form I suppose and ... ?

**Comment by shannah** [comment]
Yes.  Just the generated Form class.  And the XML for it, which is located in the res/guibuilder folder of the project.

Also.  Make sure you update your project libs so that you are working with the latest.  Just tried another sample from scratch.   And result was fine.  Didn't have to do anything with scrolling.

**Comment by seinecle** [comment]
I re created a Form from scratch. Refreshed libs. Same result. The class after I added the Components:

```
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.clementlevallois.myfirstapp;

/**
 * GUI builder created Form
 *
 * @author C. Levallois
 */
public class FormAutoLayout extends com.codename1.ui.Form {

    public FormAutoLayout() {
        this(com.codename1.ui.util.Resources.getGlobalResources());
    }
    
    public FormAutoLayout(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    private com.codename1.ui.Container gui_Container = new com.codename1.ui.Container(new com.codename1.ui.layouts.BorderLayout());
    private com.codename1.ui.Label gui_Label = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_1 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_2 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_3 = new com.codename1.ui.Label();
    private com.codename1.ui.Label gui_Label_4 = new com.codename1.ui.Label();
    private com.codename1.ui.Button gui_Button = new com.codename1.ui.Button();


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.LayeredLayout());
        setInlineStylesTheme(resourceObjectInstance);
                setInlineStylesTheme(resourceObjectInstance);
        setTitle("FormAutoLayout");
        setName("FormAutoLayout");
        addComponent(gui_Container);
        gui_Container.setPreferredSizeStr("166.93121mm 105.02646mm");
                gui_Container.setInlineStylesTheme(resourceObjectInstance);
        gui_Container.setName("Container");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Container.getParent().getLayout()).setInsets(gui_Container, "0.0mm 0.0mm 50.0% 0.0mm").setReferenceComponents(gui_Container, "-1 -1 -1 -1").setReferencePositions(gui_Container, "0.0 0.0 0.0 0.0");
        gui_Container.addComponent(com.codename1.ui.layouts.BorderLayout.CENTER, gui_Label);
        gui_Container.addComponent(com.codename1.ui.layouts.BorderLayout.NORTH, gui_Label_1);
        gui_Container.addComponent(com.codename1.ui.layouts.BorderLayout.SOUTH, gui_Label_2);
        gui_Container.addComponent(com.codename1.ui.layouts.BorderLayout.EAST, gui_Label_3);
        gui_Container.addComponent(com.codename1.ui.layouts.BorderLayout.WEST, gui_Label_4);
        gui_Label.setText("Label");
                gui_Label.setInlineStylesTheme(resourceObjectInstance);
        gui_Label.setName("Label");
        gui_Label_1.setText("Label");
                gui_Label_1.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_1.setName("Label_1");
        gui_Label_2.setText("Label");
                gui_Label_2.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_2.setName("Label_2");
        gui_Label_3.setText("Label");
                gui_Label_3.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_3.setName("Label_3");
        gui_Label_4.setText("Label");
                gui_Label_4.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_4.setName("Label_4");
        addComponent(gui_Button);
        gui_Container.setPreferredSizeStr("166.93121mm 105.02646mm");
                gui_Container.setInlineStylesTheme(resourceObjectInstance);
        gui_Container.setName("Container");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Container.getParent().getLayout()).setInsets(gui_Container, "0.0mm 0.0mm 50.0% 0.0mm").setReferenceComponents(gui_Container, "-1 -1 -1 -1").setReferencePositions(gui_Container, "0.0 0.0 0.0 0.0");
        gui_Button.setText("Button");
                gui_Button.setInlineStylesTheme(resourceObjectInstance);
        gui_Button.setName("Button");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Button.getParent().getLayout()).setInsets(gui_Button, "auto auto 26.54088% 42.31379%").setReferenceComponents(gui_Button, "-1 -1 -1 -1").setReferencePositions(gui_Button, "0.0 0.0 0.0 0.0");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}

```

**Comment by shannah** [comment]
Thanks.  I see what's going on.  The form is scrollable by default - and the GUIBuilder non-checking of it isn't explicitly disabling it.  I'll fix this on Monday.  Workaround:

Toggle the "Scrollable Y" property of the form on then off, and save.  This will fix it.  (I tried your actual class in my project and was able to reproduce the issue.  Manually setting Scrollable to false fixed it for me.

**Comment by seinecle** [comment]
Thanks!

**Comment by seinecle** [comment]
Indeed that was it.
