### ISSUE TITLE
[BUG?] addMarker and removeMarker in a MapContainer (with videos)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2406]
References: https://stackoverflow.com/questions/50203223/codename-one-correct-use-of-addmarkerpin-coordinate-of-mapcontainer-video

After several trials, the following code works (almost) correctly on Android (it's a class that extends MapContainer):
https://gist.github.com/jsfan3/4245f9cc9a790ebc028d9690e79bf5bf

To test this code, you can use this snippet:
https://gist.github.com/jsfan3/cc0899a1c4b071eacd71ea8bbe1bdfe2

The problems are that:

- I need to give a new instance of a Component to addMarker, because I cannot reuse the same Component because it is not properly removed; 
- to remove a marker I need to use removeMarker and removeMapObject together and in this order (I tried other solutions but they don't work);
- the code seems to work (almost) correctly only on Android: on iOS it doesn't work. The are also few issues in the simulator.

[You can see three videos in the attached zip ](https://github.com/codenameone/CodenameOne/files/1983512/Video.zip):
- Android (it's quite ok, note in the video that one of the added markers is not visible).
- iOS (the new markers are not visible).
- Simulator (the initial marker is not visible and the markers are in a wrong position after scrolling the map).

**Comment by shannah** [comment]
Fixed

https://github.com/codenameone/codenameone-google-maps/commit/4be2621d701b68450878956bae3fc3ac40588360

https://github.com/codenameone/codenameone-google-maps/commit/24640f3fb90fbb38faedb57cf383b8fdf9fcfd2c

**Comment by jsfan3** [comment]
Thank you! When can I update the library in my project?

**Comment by shannah** [comment]
Download it immediately at https://github.com/codenameone/codenameone-google-maps/blob/master/GoogleMaps.cn1lib

Or wait until next update of extensions lib to update through Codename One settings.   That will be soon, (usually a few days).  But don't know exactly.

**Comment by shannah** [comment]
It is working fine for me.  iPhone 8 device.  iOS 11.3.1

My Code:

~~~~
public void showOnMap2() {
        Coord location = new Coord(37.7831, -122.401558);
        Coord initialCoordinate = location;
        Form mapDemo = new Form("Maps", new LayeredLayout());
        if (BrowserComponent.isNativeBrowserSupported()) {
            System.out.println("Browser Component Supported");
            MapContainer mc = new MyMapContainer();
            MyMapContainer mapContainer = (MyMapContainer) mc;
            mapDemo.add(mc);
            mapContainer.addMarker(initialCoordinate);
            mapContainer.zoom(initialCoordinate, 18);
            mapContainer.addTapListener(e -> {
                Coord userTappedCoord = mapContainer.getCoordAtPosition(e.getX(), e.getY());
                Log.p("userTappedCoord: " + userTappedCoord);
                mapContainer.addMarker(userTappedCoord);
                
            });

            //mc.setShowMyLocation(true);
        } else {
            // iOS Screenshot process...
            mapDemo.add(new Label("Loading, please wait...."));
        }
        mapDemo.show();
    }

public class MyMapContainer extends MapContainer {

        private Label pin;
        private Location markerLocation = new Location(0.0, 0.0);
        MapObject mapObject = null;

        /**
         * Constructor that creates a default pinVector to be used with
         * addMarker(Coord coordinate)
         */
        public MyMapContainer() {
            super(JS_API_KEY);
            Style s = new Style();
            s.setFgColor(ColorUtil.BLACK);
            pin = new Label(FontImage.createMaterial(FontImage.MATERIAL_PLACE, s, 10));
        }

        /**
         * Constructor
         *
         * @param pinVector to be used with addMarker(Coord coordinate)
         */
        public MyMapContainer(Image pinVector) {
            this();
            if (pinVector != null) {
                pin = new Label(pinVector);
            }
        }

        /**
         * Adds a single marker (removes the previous one, if any)
         *
         * @param coordinate
         */
        public void addMarker(Coord coordinate) {
            if (mapObject != null) {
                this.removeMapObject(mapObject);
                Log.p("Marker removed");
            }
            mapObject = this.addMarker(pin, coordinate);
            //this.setCameraPosition(coordinate);
            Log.p("Marker added to the coordinate: " + coordinate.toString());

            markerLocation.setLatitude(coordinate.getLatitude());
            markerLocation.setLongitude(coordinate.getLongitude());
            revalidate();
        }

        /**
         * Returns the marker location
         *
         * @return markerLocation
         */
        public Location getMarkerLocation() {
            return markerLocation;
        }

    }
~~~~

**Comment by jsfan3** [comment]
Thank you very much. I tested your code in the same device farm and there is still the same issue on iPhone, so that means that the problem is the device farm itself. I hope to buy soon an actual iPhone to do my tests.
